POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
    "name": "John Doe",
    "occupation": "Student",
    "gender": "other",
    "ssn":"2390889-2343",
    "dateOfBirth": "1967-07-23"
}